export const FETCH_ALL_LVL = 'FETCH_ALL_LVL';
export const FETCH_ALL_ORIGIN = 'FETCH_ALL_ORIGIN';
export const FETCH_ALL_DESTINATION = 'FETCH_ALL_DESTINATION';
export const FETCH_ALL_CARGO_TYPE = 'FETCH_ALL_CARGO_TYPE';
export const FETCH_ALL_CHARGE_NAME = 'FETCH_ALL_CHARGE_NAME';
export const FETCH_ALL_LOAD_TYPE = 'FETCH_ALL_LOAD_TYPE';